// flow-typed signature: 68f82a71aa6344e2928276c41b4cfc51
// flow-typed version: <<STUB>>/nanoid_v1.0.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nanoid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nanoid' {
  declare module.exports: (size?: number) => string
}
